import {NAME} from './constants';

export const REQUEST_CHAT = `${NAME}.REQUEST_CHAT`;
export const REQUEST_CHAT_SUCCESS = `${NAME}.REQUEST_CHAT_SUCCESS`;
export const REQUEST_CHAT_FAILURE = `${NAME}.REQUEST_CHAT_FAILURE`;

export const REQUEST_CHAT_UPDATE = `${NAME}.REQUEST_CHAT_UPDATE`;
export const REQUEST_CHAT_UPDATE_SUCCESS = `${NAME}.REQUEST_CHAT_UPDATE_SUCCESS`;
export const REQUEST_CHAT_UPDATE_FAILURE = `${NAME}.REQUEST_CHAT_UPDATE_FAILURE`;

export const NORMALIZE = `${NAME}.NORMALIZE`;
